export default {
    carts: 'carts',
    cart_items: 'cart_items',
    cart_refunds: 'cart_refunds',
    exchange_rates: 'exchange_rates',
    heros: 'heros',
    payments: 'payments',
    master_types: 'master_types',
    media: 'media',
    package_types: 'package_types',
    product_accent_messages: 'product_accent_messages',
    product_artists: 'product_artists',
    product_collections: 'product_collections',
    product_color_swatches: 'product_color_swatches',
    product_cross_sells: 'product_cross_sells',
    product_data_tables: 'product_data_tables',
    product_variant_skus: 'product_variant_skus',
    product_variants: 'product_variants',
    products: 'products',
    tax_nexus: 'tax_nexus',
    tenant_members: 'tenant_members',
    tenants: 'tenants'
};
